spring:
  messages:
    basename: validation
  mvc:
    view:      prefix: /
      suffix: .jsp
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/voitures
    username: root
    password: 
    driverClassName: com.mysql.cj.jdbc.Driver
server:
  port: 8888