-- MySQL Script generated by MySQL Workbench
-- 09/29/19 17:18:59
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE = 'TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema voitures
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `voitures`;

-- -----------------------------------------------------
-- Schema voitures
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `voitures` DEFAULT CHARACTER SET latin1;
USE `voitures`;

-- -----------------------------------------------------
-- Table `voitures`.`adresse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `voitures`.`adresse`;

CREATE TABLE IF NOT EXISTS `voitures`.`adresse`
(
    `id`                 BIGINT(20)   NOT NULL AUTO_INCREMENT,
    `code_postal`        VARCHAR(45)  NOT NULL,
    `complement_adresse` VARCHAR(150) NULL DEFAULT NULL,
    `libelle_voie`       VARCHAR(200) NOT NULL,
    `numero_voie`        INT(11)      NULL DEFAULT NULL,
    `pays`               VARCHAR(100) NOT NULL,
    `ville`              VARCHAR(100) NOT NULL,
    PRIMARY KEY (`id`)
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = latin1;

CREATE UNIQUE INDEX `UK7ggrp5h5vfkokp1jc064uahl7` ON `voitures`.`adresse` (`numero_voie` ASC, `libelle_voie` ASC,
                                                                           `complement_adresse` ASC, `code_postal` ASC,
                                                                           `ville` ASC, `pays` ASC);


-- -----------------------------------------------------
-- Table `voitures`.`client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `voitures`.`client`;

CREATE TABLE IF NOT EXISTS `voitures`.`client`
(
    `id`                             BIGINT(20)   NOT NULL AUTO_INCREMENT,
    `date_creation_client`           DATETIME     NOT NULL,
    `date_derniere_miseajour_client` DATETIME     NOT NULL,
    `email`                          VARCHAR(100) NOT NULL,
    `nom`                            VARCHAR(100) NOT NULL,
    `numero_tel`                     VARCHAR(75)  NULL DEFAULT NULL,
    `prenom`                         VARCHAR(100) NOT NULL,
    `adresse_id`                     BIGINT(20)   NOT NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT `FK29btfh0bmn7ww7p2ksjlm1p`
        FOREIGN KEY (`adresse_id`)
            REFERENCES `voitures`.`adresse` (`id`)
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = latin1;

CREATE UNIQUE INDEX `UK_bfgjs3fem0hmjhvih80158x29` ON `voitures`.`client` (`email` ASC);

CREATE UNIQUE INDEX `UK5h5on1enuxeysbjgcfc8ivah6` ON `voitures`.`client` (`nom` ASC, `prenom` ASC, `numero_tel` ASC,
                                                                          `email` ASC, `adresse_id` ASC);

CREATE UNIQUE INDEX `UK_rxqstleojnslo5yryiawhayw3` ON `voitures`.`client` (`numero_tel` ASC);

CREATE INDEX `FK29btfh0bmn7ww7p2ksjlm1p` ON `voitures`.`client` (`adresse_id` ASC);


-- -----------------------------------------------------
-- Table `voitures`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `voitures`.`role`;

CREATE TABLE IF NOT EXISTS `voitures`.`role`
(
    `id`  BIGINT(20)   NOT NULL AUTO_INCREMENT,
    `nom` VARCHAR(100) NOT NULL,
    PRIMARY KEY (`id`)
)
    ENGINE = InnoDB
    AUTO_INCREMENT = 4
    DEFAULT CHARACTER SET = latin1;

CREATE UNIQUE INDEX `UK_6u1k6pqq7suwepwcfskympy3s` ON `voitures`.`role` (`nom` ASC);


-- -----------------------------------------------------
-- Table `voitures`.`employe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `voitures`.`employe`;

CREATE TABLE IF NOT EXISTS `voitures`.`employe`
(
    `id`          BIGINT(20)   NOT NULL AUTO_INCREMENT,
    `create_time` DATETIME     NOT NULL,
    `email`       VARCHAR(100) NOT NULL,
    `nom`         VARCHAR(100) NOT NULL,
    `password`    VARCHAR(100) NOT NULL,
    `prenom`      VARCHAR(100) NOT NULL,
    `username`    VARCHAR(100) NOT NULL,
    `role_id`     BIGINT(20)   NOT NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT `FKi7qruj3ctwgf193i4vhgni8a9`
        FOREIGN KEY (`role_id`)
            REFERENCES `voitures`.`role` (`id`)
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = latin1;

CREATE UNIQUE INDEX `UK5d1yph1s4g7865kpvmwo5cngk` ON `voitures`.`employe` (`nom` ASC, `prenom` ASC, `username` ASC, `email` ASC);

CREATE UNIQUE INDEX `UK_13xeyi3ex32ti4t6i4sotp28i` ON `voitures`.`employe` (`email` ASC);

CREATE UNIQUE INDEX `UK_3eu8efvye6ym3j7quu2359tn4` ON `voitures`.`employe` (`username` ASC);

CREATE INDEX `FKi7qruj3ctwgf193i4vhgni8a9` ON `voitures`.`employe` (`role_id` ASC);


-- -----------------------------------------------------
-- Table `voitures`.`status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `voitures`.`status`;

CREATE TABLE IF NOT EXISTS `voitures`.`status`
(
    `id`  BIGINT(20)   NOT NULL AUTO_INCREMENT,
    `nom` VARCHAR(100) NOT NULL,
    PRIMARY KEY (`id`)
)
    ENGINE = InnoDB
    AUTO_INCREMENT = 7
    DEFAULT CHARACTER SET = latin1;

CREATE UNIQUE INDEX `UK_d8r35q1aejxj6wjb09iaw7v5a` ON `voitures`.`status` (`nom` ASC);


-- -----------------------------------------------------
-- Table `voitures`.`commande`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `voitures`.`commande`;

CREATE TABLE IF NOT EXISTS `voitures`.`commande`
(
    `id`               BIGINT(20) NOT NULL AUTO_INCREMENT,
    `client_id`        BIGINT(20) NOT NULL,
    `employe_id`       BIGINT(20) NOT NULL,
    `statut_livraison` BIGINT(20) NOT NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT `FK79q1nginx2k3m83vi3bt3rlon`
        FOREIGN KEY (`client_id`)
            REFERENCES `voitures`.`client` (`id`),
    CONSTRAINT `FKgmjxre8plwya7d03jragug1yc`
        FOREIGN KEY (`employe_id`)
            REFERENCES `voitures`.`employe` (`id`),
    CONSTRAINT `FKk1mdr59ip81jormy7mfruu0k3`
        FOREIGN KEY (`statut_livraison`)
            REFERENCES `voitures`.`status` (`id`)
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = latin1;

CREATE INDEX `FK79q1nginx2k3m83vi3bt3rlon` ON `voitures`.`commande` (`client_id` ASC);

CREATE INDEX `FKgmjxre8plwya7d03jragug1yc` ON `voitures`.`commande` (`employe_id` ASC);

CREATE INDEX `FKk1mdr59ip81jormy7mfruu0k3` ON `voitures`.`commande` (`statut_livraison` ASC);


-- -----------------------------------------------------
-- Table `voitures`.`devis`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `voitures`.`devis`;

CREATE TABLE IF NOT EXISTS `voitures`.`devis`
(
    `id`                  BIGINT(20) NOT NULL AUTO_INCREMENT,
    `date_creation_devis` DATETIME   NOT NULL,
    `delai_devis`         INT(11)    NOT NULL,
    `prixht`              FLOAT      NOT NULL,
    `prixttc`             FLOAT      NOT NULL,
    `client_id`           BIGINT(20) NOT NULL,
    `employe_id`          BIGINT(20) NOT NULL,
    `status_devis`        BIGINT(20) NOT NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT `FK5e9ri93wudunww5t9eqenq0bp`
        FOREIGN KEY (`client_id`)
            REFERENCES `voitures`.`client` (`id`),
    CONSTRAINT `FK8uero2u8a5woi53lq0eq6e7mw`
        FOREIGN KEY (`status_devis`)
            REFERENCES `voitures`.`status` (`id`),
    CONSTRAINT `FKry38t8jj58hpxqlale0rvcfwu`
        FOREIGN KEY (`employe_id`)
            REFERENCES `voitures`.`employe` (`id`)
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = latin1;

CREATE INDEX `FK5e9ri93wudunww5t9eqenq0bp` ON `voitures`.`devis` (`client_id` ASC);

CREATE INDEX `FKry38t8jj58hpxqlale0rvcfwu` ON `voitures`.`devis` (`employe_id` ASC);

CREATE INDEX `FK8uero2u8a5woi53lq0eq6e7mw` ON `voitures`.`devis` (`status_devis` ASC);


-- -----------------------------------------------------
-- Table `voitures`.`stock`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `voitures`.`stock`;

CREATE TABLE IF NOT EXISTS `voitures`.`stock`
(
    `id`                BIGINT(20)   NOT NULL AUTO_INCREMENT,
    `nom_produit`       VARCHAR(100) NOT NULL,
    `prix_produit`      FLOAT        NOT NULL,
    `qte_produit_dispo` INT(11)      NOT NULL DEFAULT 0,
    `qte_reserve`       INT(11)      NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`)
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = latin1;

CREATE UNIQUE INDEX `UK_e1rjbguboxvigyn681wilpdo5` ON `voitures`.`stock` (`nom_produit` ASC);


-- -----------------------------------------------------
-- Table `voitures`.`ligne_commande`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `voitures`.`ligne_commande`;

CREATE TABLE IF NOT EXISTS `voitures`.`ligne_commande`
(
    `id`                           BIGINT(20) NOT NULL AUTO_INCREMENT,
    `date_creation_ligne_commande` DATETIME   NOT NULL,
    `delai_livraison`              INT(11)    NOT NULL,
    `qte_commande`                 INT(11)    NOT NULL DEFAULT 1,
    `commande_id`                  BIGINT(20) NOT NULL,
    `status_id`                    BIGINT(20) NOT NULL,
    `stock_id`                     BIGINT(20) NOT NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT `FKaff2bjyreiuyi723relg10spm`
        FOREIGN KEY (`commande_id`)
            REFERENCES `voitures`.`commande` (`id`),
    CONSTRAINT `FKdwvel8taeu1on2swx98qvy5mq`
        FOREIGN KEY (`stock_id`)
            REFERENCES `voitures`.`stock` (`id`),
    CONSTRAINT `FKo6i5yb1vuifoo9aebxxmay11m`
        FOREIGN KEY (`status_id`)
            REFERENCES `voitures`.`status` (`id`)
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = latin1;

CREATE UNIQUE INDEX `UKaqwibo5pd3b2h6qnfpu5p3dgv` ON `voitures`.`ligne_commande` (`delai_livraison` ASC, `qte_commande`
                                                                                  ASC, `commande_id` ASC, `stock_id`
                                                                                  ASC);

CREATE INDEX `FKaff2bjyreiuyi723relg10spm` ON `voitures`.`ligne_commande` (`commande_id` ASC);

CREATE INDEX `FKo6i5yb1vuifoo9aebxxmay11m` ON `voitures`.`ligne_commande` (`status_id` ASC);

CREATE INDEX `FKdwvel8taeu1on2swx98qvy5mq` ON `voitures`.`ligne_commande` (`stock_id` ASC);


-- -----------------------------------------------------
-- Table `voitures`.`ligne_produit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `voitures`.`ligne_produit`;

CREATE TABLE IF NOT EXISTS `voitures`.`ligne_produit`
(
    `id`          BIGINT(20) NOT NULL AUTO_INCREMENT,
    `prix_ligne`  FLOAT      NOT NULL DEFAULT 0,
    `qte_produit` INT(11)    NOT NULL DEFAULT 1,
    `devis_id`    BIGINT(20) NOT NULL,
    `stock_id`    BIGINT(20) NOT NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT `FK89rf3u6jdavaa5i4pkofey11t`
        FOREIGN KEY (`stock_id`)
            REFERENCES `voitures`.`stock` (`id`),
    CONSTRAINT `FKeoyt6ylnr0mqnpitf6ny0nsfr`
        FOREIGN KEY (`devis_id`)
            REFERENCES `voitures`.`devis` (`id`)
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = latin1;

CREATE UNIQUE INDEX `UK8aij55ka5fbnwnhmdeewvqpot` ON `voitures`.`ligne_produit` (`qte_produit` ASC, `prix_ligne` ASC, `devis_id` ASC, `stock_id` ASC);

CREATE INDEX `FKeoyt6ylnr0mqnpitf6ny0nsfr` ON `voitures`.`ligne_produit` (`devis_id` ASC);

CREATE INDEX `FK89rf3u6jdavaa5i4pkofey11t` ON `voitures`.`ligne_produit` (`stock_id` ASC);


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
