-- MySQL Script generated by MySQL Workbench
-- Tue Sep 24 14:06:31 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema voitures
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `voitures` ;

-- -----------------------------------------------------
-- Schema voitures
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `voitures` DEFAULT CHARACTER SET utf8 ;
USE `voitures` ;

-- -----------------------------------------------------
-- Table `voitures`.`stock`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `voitures`.`stock` ;

CREATE TABLE IF NOT EXISTS `voitures`.`stock` (
  `idStock` INT NOT NULL AUTO_INCREMENT,
  `nomProduit` VARCHAR(100) NOT NULL,
  `prixProduit` FLOAT NOT NULL,
  `qteProduit` INT NOT NULL DEFAULT 0,
  `qteReserve` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idStock`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `voitures`.`adresse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `voitures`.`adresse` ;

CREATE TABLE IF NOT EXISTS `voitures`.`adresse` (
  `idAdresse` INT NOT NULL AUTO_INCREMENT,
  `numeroVoie` INT NULL,
  `libelleVoie` VARCHAR(200) NOT NULL,
  `complementAdresse` VARCHAR(200) NULL,
  `codePostal` VARCHAR(45) NOT NULL,
  `ville` VARCHAR(75) NOT NULL,
  PRIMARY KEY (`idAdresse`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `voitures`.`client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `voitures`.`client` ;

CREATE TABLE IF NOT EXISTS `voitures`.`client` (
  `idClient` INT NOT NULL AUTO_INCREMENT,
  `nomClient` VARCHAR(100) NOT NULL,
  `prenomClient` VARCHAR(100) NOT NULL,
  `numeroTelClient` VARCHAR(75) NULL,
  `adresseMail` VARCHAR(100) NOT NULL,
  `dateCreation` DATETIME NOT NULL DEFAULT NOW(),
  `DateMiseAJour` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `adresse_idAdresse` INT NOT NULL,
  PRIMARY KEY (`idClient`, `adresse_idAdresse`),
  CONSTRAINT `fk_client_adresse1`
    FOREIGN KEY (`adresse_idAdresse`)
    REFERENCES `voitures`.`adresse` (`idAdresse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `adresseMail_UNIQUE` ON `voitures`.`client` (`adresseMail` ASC) VISIBLE;

CREATE UNIQUE INDEX `numeroTelClient_UNIQUE` ON `voitures`.`client` (`numeroTelClient` ASC) VISIBLE;

CREATE INDEX `fk_client_adresse1_idx` ON `voitures`.`client` (`adresse_idAdresse` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `voitures`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `voitures`.`role` ;

CREATE TABLE IF NOT EXISTS `voitures`.`role` (
  `idRole` INT NOT NULL AUTO_INCREMENT,
  `nomRole` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idRole`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `nomRole_UNIQUE` ON `voitures`.`role` (`nomRole` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `voitures`.`employe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `voitures`.`employe` ;

CREATE TABLE IF NOT EXISTS `voitures`.`employe` (
  `idEmploye` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NULL,
  `password` VARCHAR(100) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `role_idRole` INT NOT NULL,
  PRIMARY KEY (`idEmploye`),
  CONSTRAINT `fk_employe_role1`
    FOREIGN KEY (`role_idRole`)
    REFERENCES `voitures`.`role` (`idRole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `fk_employe_role1_idx` ON `voitures`.`employe` (`role_idRole` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `voitures`.`status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `voitures`.`status` ;

CREATE TABLE IF NOT EXISTS `voitures`.`status` (
  `idStatus` INT NOT NULL AUTO_INCREMENT,
  `nomStatus` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idStatus`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `nomStatus_UNIQUE` ON `voitures`.`status` (`nomStatus` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `voitures`.`devis`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `voitures`.`devis` ;

CREATE TABLE IF NOT EXISTS `voitures`.`devis` (
  `idDevis` INT NOT NULL AUTO_INCREMENT,
  `dateCreationDevis` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `delaiDevis` TIMESTAMP NOT NULL,
  `prixHT` FLOAT NOT NULL DEFAULT 0,
  `prixTTC` FLOAT NOT NULL DEFAULT 0,
  `client_idclient` INT NOT NULL,
  `user_idUser` INT NOT NULL,
  `statut_devis` INT NOT NULL,
  PRIMARY KEY (`idDevis`, `user_idUser`),
  CONSTRAINT `fk_devis_client1`
    FOREIGN KEY (`client_idclient`)
    REFERENCES `voitures`.`client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_devis_user1`
    FOREIGN KEY (`user_idUser`)
    REFERENCES `voitures`.`employe` (`idEmploye`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_devis_status1`
    FOREIGN KEY (`statut_devis`)
    REFERENCES `voitures`.`status` (`idStatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_devis_client1_idx` ON `voitures`.`devis` (`client_idclient` ASC) VISIBLE;

CREATE INDEX `fk_devis_user1_idx` ON `voitures`.`devis` (`user_idUser` ASC) VISIBLE;

CREATE INDEX `fk_devis_status1_idx` ON `voitures`.`devis` (`statut_devis` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `voitures`.`commande`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `voitures`.`commande` ;

CREATE TABLE IF NOT EXISTS `voitures`.`commande` (
  `idCommande` INT NOT NULL AUTO_INCREMENT,
  `employe_idEmploye` INT NOT NULL,
  `statut_livraison` INT NOT NULL,
  `client_idClient` INT NOT NULL,
  PRIMARY KEY (`idCommande`, `employe_idEmploye`),
  CONSTRAINT `fk_commande_employé1`
    FOREIGN KEY (`employe_idEmploye`)
    REFERENCES `voitures`.`employe` (`idEmploye`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commande_status1`
    FOREIGN KEY (`statut_livraison`)
    REFERENCES `voitures`.`status` (`idStatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commande_client1`
    FOREIGN KEY (`client_idClient`)
    REFERENCES `voitures`.`client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_commande_employé1_idx` ON `voitures`.`commande` (`employe_idEmploye` ASC) VISIBLE;

CREATE INDEX `fk_commande_status1_idx` ON `voitures`.`commande` (`statut_livraison` ASC) VISIBLE;

CREATE INDEX `fk_commande_client1_idx` ON `voitures`.`commande` (`client_idClient` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `voitures`.`produits`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `voitures`.`produits` ;

CREATE TABLE IF NOT EXISTS `voitures`.`produits` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `voitures`.`ligneProduit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `voitures`.`ligneProduit` ;

CREATE TABLE IF NOT EXISTS `voitures`.`ligneProduit` (
  `idLigneProduit` INT NOT NULL AUTO_INCREMENT,
  `stock_idStock` INT NOT NULL,
  `devis_idDevis` INT NOT NULL,
  `qteProduit` INT NOT NULL DEFAULT 1,
  `prixLigne` FLOAT NOT NULL,
  PRIMARY KEY (`idLigneProduit`, `stock_idStock`, `devis_idDevis`),
  CONSTRAINT `fk_produit_has_devis_produit`
    FOREIGN KEY (`stock_idStock`)
    REFERENCES `voitures`.`stock` (`idStock`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produit_has_devis_devis1`
    FOREIGN KEY (`devis_idDevis`)
    REFERENCES `voitures`.`devis` (`idDevis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_produit_has_devis_devis1_idx` ON `voitures`.`ligneProduit` (`devis_idDevis` ASC) VISIBLE;

CREATE INDEX `fk_produit_has_devis_produit_idx` ON `voitures`.`ligneProduit` (`stock_idStock` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `voitures`.`ligneCommande`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `voitures`.`ligneCommande` ;

CREATE TABLE IF NOT EXISTS `voitures`.`ligneCommande` (
  `idLigneCommande` INT NOT NULL AUTO_INCREMENT,
  `stock_idStock` INT NOT NULL,
  `commande_idCommande` INT NOT NULL,
  `qteCommande` INT NOT NULL DEFAULT 1,
  `delaisLivraison` INT NOT NULL,
  `status_idStatus` INT NOT NULL,
  `dateCreation` DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (`idLigneCommande`, `stock_idStock`, `commande_idCommande`),
  CONSTRAINT `fk_stock_has_commande_stock1`
    FOREIGN KEY (`stock_idStock`)
    REFERENCES `voitures`.`stock` (`idStock`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stock_has_commande_commande1`
    FOREIGN KEY (`commande_idCommande`)
    REFERENCES `voitures`.`commande` (`idCommande`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ligneCommande_status1`
    FOREIGN KEY (`status_idStatus`)
    REFERENCES `voitures`.`status` (`idStatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_stock_has_commande_commande1_idx` ON `voitures`.`ligneCommande` (`commande_idCommande` ASC) VISIBLE;

CREATE INDEX `fk_stock_has_commande_stock1_idx` ON `voitures`.`ligneCommande` (`stock_idStock` ASC) VISIBLE;

CREATE INDEX `fk_ligneCommande_status1_idx` ON `voitures`.`ligneCommande` (`status_idStatus` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `voitures`.`role`
-- -----------------------------------------------------
START TRANSACTION;
USE `voitures`;
INSERT INTO `voitures`.`role` (`idRole`, `nomRole`) VALUES (1, 'admin');
INSERT INTO `voitures`.`role` (`idRole`, `nomRole`) VALUES (2, 'magasinier');
INSERT INTO `voitures`.`role` (`idRole`, `nomRole`) VALUES (3, 'commercial');

COMMIT;


-- -----------------------------------------------------
-- Data for table `voitures`.`status`
-- -----------------------------------------------------
START TRANSACTION;
USE `voitures`;
INSERT INTO `voitures`.`status` (`idStatus`, `nomStatus`) VALUES (1, 'commande livre');
INSERT INTO `voitures`.`status` (`idStatus`, `nomStatus`) VALUES (2, 'commande recue');
INSERT INTO `voitures`.`status` (`idStatus`, `nomStatus`) VALUES (3, 'commande annulee');
INSERT INTO `voitures`.`status` (`idStatus`, `nomStatus`) VALUES (4, 'devis valide');
INSERT INTO `voitures`.`status` (`idStatus`, `nomStatus`) VALUES (5, 'devis annule');
INSERT INTO `voitures`.`status` (`idStatus`, `nomStatus`) VALUES (6, 'devis en cours');

COMMIT;

